// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftParen-0]
	_ = x[RightParen-1]
	_ = x[LeftBrace-2]
	_ = x[RightBrace-3]
	_ = x[Comma-4]
	_ = x[TokenTypeDot-5]
	_ = x[Minus-6]
	_ = x[Plus-7]
	_ = x[Semicolon-8]
	_ = x[Slash-9]
	_ = x[Star-10]
	_ = x[Bang-11]
	_ = x[BangEqual-12]
	_ = x[Equal-13]
	_ = x[EqualEqual-14]
	_ = x[Greater-15]
	_ = x[GreaterEqual-16]
	_ = x[Less-17]
	_ = x[LessEqual-18]
	_ = x[Identifier-19]
	_ = x[String-20]
	_ = x[Number-21]
	_ = x[And-22]
	_ = x[Class-23]
	_ = x[Else-24]
	_ = x[False-25]
	_ = x[Fun-26]
	_ = x[For-27]
	_ = x[If-28]
	_ = x[Nil-29]
	_ = x[Or-30]
	_ = x[Print-31]
	_ = x[Return-32]
	_ = x[Super-33]
	_ = x[This-34]
	_ = x[True-35]
	_ = x[Var-36]
	_ = x[While-37]
	_ = x[EOF-38]
}

const _TokenType_name = "LeftParenRightParenLeftBraceRightBraceCommaTokenTypeDotMinusPlusSemicolonSlashStarBangBangEqualEqualEqualEqualGreaterGreaterEqualLessLessEqualIdentifierStringNumberAndClassElseFalseFunForIfNilOrPrintReturnSuperThisTrueVarWhileEOF"

var _TokenType_index = [...]uint8{0, 9, 19, 28, 38, 43, 55, 60, 64, 73, 78, 82, 86, 95, 100, 110, 117, 129, 133, 142, 152, 158, 164, 167, 172, 176, 181, 184, 187, 189, 192, 194, 199, 205, 210, 214, 218, 221, 226, 229}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
